# These versions will NOT be allowed to connect.
# These versions MUST be the version number. You can check the numbers here: https://wiki.vg/Protocol_version_numbers
# By default, all versions are listed here.
versions:
  - 47
  - 107
  - 108
  - 109
  - 110
  - 210
  - 315
  - 316
  - 335
  - 338
  - 340
  - 393
  - 401
  - 404
  - 477
  - 480
  - 485
  - 490
  - 498
  - 573
  - 575
  - 578
  - 735
  - 736
  - 751
  - 753
  - 754
  - 755
  - 756
  - 757
  - 758
  - 759
  - 760 # this will show up as 1.19.2 because 1.19.1 and .2 share the same protocol version
  - 761

# Send this message if someone connects with a blocked version.
# Use {VERSIONS} to show what versions your server uses. It will display like "1.8 to 1.16.3" or whatever.
# If you don't want to use {VERSIONS}, just remove it.
disconnect-message: "<red>You cannot connect with this version! We only allow version(s) {VERSIONS}.</red>"

# This will say "Player is connecting with protocol version" when someone joins.
# This is off by default to not spam your console, but you can enable it for debug reasons.
log-connection-versions: false

# No touch please :)
config-version: 5